version: '3'

services:

  db:
    image: postgres:12.2-alpine
    container_name: db
    tty: true
    networks:
      - rocks
    volumes:
      - ./data/db:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
      - POSTGRES_DB=videos

  api:
    image: ordnaelmedeiros/videos
    container_name: videos
#    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s node /app/index.js
    build:
      context: ./videos
      dockerfile: ./src/main/docker/Dockerfile.build
    volumes:
      - ./data/m2:/root/.m2
      - ./videos:/home/app
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    ports:
      - 8080:8080
    networks:
      - rocks
    depends_on:
      - db

networks:
  rocks:
    driver: bridge