CREATE TABLE CATEGORIES (
	ID UUID NOT NULL,
    NAME VARCHAR(255),
    DESCRIPTION TEXT,
    IS_ACTIVE BOOLEAN,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE GENRES (
	ID UUID NOT NULL,
    NAME VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,
    PRIMARY KEY (ID)
);