CREATE TABLE CAST_MEMBERS (
	ID UUID NOT NULL,
    NAME VARCHAR(255),
    TYPE VARCHAR(20),
    IS_ACTIVE BOOLEAN,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,
    PRIMARY KEY (ID)
);
