CREATE TABLE VIDEOS_CATEGORIES (
	VIDEO_ID UUID NOT NULL,
	CATEGORIES_ID UUID NOT NULL,
	PRIMARY KEY (VIDEO_ID, CATEGORIES_ID)
);

CREATE TABLE VIDEOS_GENRES (
	VIDEO_ID UUID NOT NULL,
	GENRES_ID UUID NOT NULL,
	PRIMARY KEY (VIDEO_ID, GENRES_ID)
);
