CREATE TABLE VIDEOS (
	ID UUID NOT NULL,
	TITLE VARCHAR(255),
    DESCRIPTION TEXT,
    YEAR_LAUNCHED NUMERIC(4),
    OPENED BOOLEAN,
    RATING VARCHAR(3),
    DURATION NUMERIC(4),
    IS_ACTIVE BOOLEAN,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,
    PRIMARY KEY (ID)
);
