name: ci-videos-build
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: mvn -f videos --batch-mode verify

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        
      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: ./videos
          file: ./videos/src/main/docker/Dockerfile.jvm
          push: true
          tags: ordnaelmedeiros/em-videos:latest